import React from 'react';

export default function ExplanationPanel() {
  return (
    <div className="explanation-panel animate-in">
      <h3>About This Dashboard</h3>
      <p>
        This dashboard visualizes the CSV output generated by the{' '}
        <code>Weighted Instruction Frequency</code> LLVM Pass. The LLVM pass
        analyzes LLVM IR, classifies instructions into instruction categories
        (<code>Arithmetic</code>, <code>Memory</code>, <code>ControlFlow</code>,{' '}
        <code>Call</code>, <code>Cast</code>, <code>Comparison</code>,{' '}
        <code>Other</code>), applies configurable weights from <code>weights.cfg</code>,
        computes function-level and basic-block-level costs using the formula{' '}
        <code>cost = count × weight</code>, detects hotspots based on a threshold,
        and exports the results to <code>results.csv</code>.
      </p>
      <div className="pipeline-row">
        <span className="pipeline-step">test.c</span>
        <span className="pipeline-arrow">→</span>
        <span className="pipeline-step">clang-14 → test.ll</span>
        <span className="pipeline-arrow">→</span>
        <span className="pipeline-step">opt-14 -weighted-inst-freq</span>
        <span className="pipeline-arrow">→</span>
        <span className="pipeline-step active">results.csv</span>
        <span className="pipeline-arrow">→</span>
        <span className="pipeline-step active">this dashboard</span>
      </div>
    </div>
  );
}
